import 'dart:collection';

import 'package:collection/collection.dart';
import 'package:rookie_yaml/src/parser/directives/directives.dart';
import 'package:rookie_yaml/src/scanner/span.dart';

part 'collections.dart';
part 'node_styles.dart';
part 'scalar.dart';

/// A custom [Equality] object for deep equality. This includes [AliasNode]s
/// which wrap their [YamlSourceNode] subclass references.
///
/// {@category yaml_nodes}
const yamlCollectionEquality = DeepCollectionEquality();

/// A YAML node with a set of node properties and its own predefine [NodeStyle].
///
/// This node is not necessarily limited to YAML's compact notation unless such
/// a notation is required when the object is being dumped.
///
/// {@category intro}
/// {@category yaml_nodes}
/// {@category dump_type}
abstract class CompactYamlNode {
  const CompactYamlNode();

  /// Style used to serialize the node within the `YAML` source string
  NodeStyle get nodeStyle;

  /// [Tag] directive describing how the node is represented natively.
  ResolvedTag? get tag => null;

  /// Anchor name that allow other nodes to reference this node.
  String? get anchor => null;

  /// Alias name that references other nodes.
  String? get alias => null;
}

/// A node parsed from a `YAML` source string.
///
/// This node represents a directed graph that can used to iterate the
/// entire YAML tree generated by the parser before any properties and styles
/// are stripped. Having this single node guarantees full access to the tree
/// irrespective of its location.
///
/// This node also acts as a compatibility layer between the parsed
/// [CompactYamlNode] and a `Dart` type. The object is always a Dart type
/// or a type inferred from a `ScalarResolver` when it comes to scalars.
///   - [Scalar] of `4` has no difference when compared to `4`
///   - [Sequence] or [Map] of values will be equal to the same [List] or
///     [Map] declared in `Dart`.
///
/// {@category intro}
/// {@category yaml_nodes}
sealed class YamlSourceNode extends CompactYamlNode with YamlTreeNode {
  /// Built-in or custom Dart type represented by this object.
  Object? get node;

  /// Span within a YAML source.
  NodeSpan get span;

  /// Whether the object is an alias.
  bool get isAlias;

  @override
  String toString() => node.toString();
}

mixin YamlTreeNode {
  /// Whether this is the first node in a cyclic linked-list.
  bool isCyclicRoot = false;

  /// Whether the object is transversible by index/key or both. If `true`, this
  /// node is a collection.
  bool get isTransversable => true;

  /// Node on the left if in a collection.
  YamlSourceNode? siblingLeft;

  /// Node on the right if in a collection.
  YamlSourceNode? siblingRight;

  /// Direct ancestor.
  YamlSourceNode? parent;

  /// Always `null` unless this value is a key.
  YamlSourceNode? childOfKey;

  /// Childred if this is a collection.
  ///
  /// Usually, [isCyclicRoot] indicates the start. If modified, you may need to
  /// define a new root or keep track of it yourself.
  final children = <YamlSourceNode>[];
}

/// Utility method for casting any [YamlSourceNode].
extension Cast on YamlSourceNode {
  /// Casts a generic [YamlSourceNode] to a valid (and known) subtype
  T cast<T extends YamlSourceNode>() => this as T;
}

/// Checks if 2 [YamlSourceNode] are equal based on the `YAML` spec.
///
/// [Scalar]s use the inferred type.
///
/// See [Node comparison](https://yaml.org/spec/1.2.2/#3213-node-comparison)
///
/// {@category yaml_nodes}
bool yamlSourceNodeDeepEqual(YamlSourceNode thiz, YamlSourceNode that) =>
    thiz == that && thiz.tag == that.tag;

/// A node that is a pointer to another node.
///
/// {@category intro}
/// {@category yaml_nodes}
/// {@category anchor_alias}
final class AliasNode extends YamlSourceNode {
  AliasNode(this.alias, this.node, this.span)
    : assert(alias.isNotEmpty, 'An alias name cannot be empty');

  /// Anchor name to [node].
  @override
  final String alias;

  @override
  final YamlSourceNode node;

  @override
  final NodeSpan span;

  @override
  bool get isAlias => true;

  @override
  List<YamlSourceNode> get children => const [];

  @override
  bool get isTransversable => false;

  @override
  NodeStyle get nodeStyle => NodeStyle.flow;

  @override
  bool operator ==(Object other) =>
      other is AliasNode && alias == other.alias && identical(node, other.node);

  @override
  int get hashCode => Object.hashAll([alias, node.hashCode]);
}
