name: dump_yaml
description: A configurable library for dumping any Dart object back to YAML.
version: 0.1.0-beta.1
repository: https://github.com/kekavc24/yaml_dart/tree/main/packages/dump_yaml
topics:
  - yaml
  - json
  - formatter

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  collection: ^1.19.1
  rookie_yaml: ^0.6.0

dev_dependencies:
  checks: ^0.3.1
  lints: ^6.0.0
  test: ^1.25.6
